# Generated by Django 4.2.13 on 2024-12-10 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierstate',
            options={'ordering': ['name'], 'verbose_name': 'Supplier State', 'verbose_name_plural': 'Supplier States'},
        ),
        migrations.AlterModelOptions(
            name='suppliertype',
            options={'ordering': ['name'], 'verbose_name': 'Supplier Type', 'verbose_name_plural': 'Supplier Types'},
        ),
    ]
