# Generated by Django 4.2.13 on 2024-08-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_alter_purchaseorder_expected_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
