# Generated by Django 4.2.13 on 2024-08-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_alter_purchaseorder_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='price_at_order',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
