# Generated by Django 4.2.13 on 2024-08-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_alter_purchaseorderitem_price_at_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproductprice',
            name='box_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
