# Generated by Django 4.2.13 on 2024-08-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_alter_supplierproductprice_box_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproductprice',
            name='supplier_article_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
