# Generated by Django 4.2.13 on 2025-06-11 22:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_first_name_alter_customer_last_name'),
        ('products', '0005_alter_product_stock_quantity'),
        ('cashregister_pdv', '0003_pdvsale_pdvsaleitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdvHoldSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(help_text='Número ou apelido da espera (ex: João, Fila 1)', max_length=50)),
                ('note', models.TextField(blank=True, help_text='Observação geral da espera', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashregister_pdv.cashregister')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PdvHoldSaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observation', models.TextField(blank=True, null=True)),
                ('hold_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cashregister_pdv.pdvholdsale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
    ]
