# Generated by Django 4.2.13 on 2025-06-29 17:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0001_initial'),
        ('cashregister_pdv', '0004_pdvholdsale_pdvholdsaleitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdvsale',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='pdvsale',
            name='change_given',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='PdvSalePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment_methods.paymentmethod')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cashregister_pdv.pdvsale')),
            ],
        ),
    ]
