# Generated by Django 4.2.13 on 2025-07-06 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashregister_pdv', '0005_remove_pdvsale_payment_method_pdvsale_change_given_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdvsale',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pdv_sales', to=settings.AUTH_USER_MODEL),
        ),
    ]
