# Generated by Django 4.2.13 on 2025-01-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_verification_code_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
