# Generated by Django 4.2.13 on 2025-04-22 11:59

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_email_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=20, validators=[customers.models.validate_no_links_or_code]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[customers.models.validate_no_links_or_code]),
        ),
    ]
