# Generated by Django 4.2.13 on 2025-06-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active_pdv',
            field=models.BooleanField(default=True, help_text='Produto ativo para exibição no PDV'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active_site',
            field=models.BooleanField(default=True, help_text='Produto ativo para exibição no site'),
        ),
    ]
